#miller / .zprofile

bins=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

brew=/usr/local/sbin

rbenv=$HOME/.rbenv/shims

cabal=$HOME/.cabal/bin

export PATH=$rbenv:$cabal:$brew:$bins

export EDITOR='vim'

export HOMEBREW_GITHUB_API_TOKEN=50c2e0549777b237eee466df6cac2e59619d6169
