#miller / .zshrc

ZSH=$HOME/.oh-my-zsh

ZSH_THEME="miller"

ZSH_TMUX_AUTOSTART="true"
DISABLE_AUTO_UPDATE="true"
DISABLE_CORRECTION="true"

plugins=(
    z git tmux tmuxinator battery vagrant colored-man
    zsh-completions
    zsh-history-substring-search
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh
source $HOME/.zprofile
source $HOME/.dots/zsh/tmuxinator.zsh
source $HOME/.dots/zsh/cmus.zsh

alias zsource="source ~/.zshrc"
alias ll="ls -Alh"
alias mv="mv -i"
