#miller / .zshrc

ZSH=$HOME/.oh-my-zsh

ZSH_THEME="miller"

ZSH_TMUX_AUTOSTART="true"
DISABLE_AUTO_UPDATE="true"
DISABLE_CORRECTION="true"

plugins=(git tmux tmuxinator battery vagrant z zsh-syntax-highlighting)


source $ZSH/oh-my-zsh.sh
source $HOME/.dots/zsh/tmuxinator.zsh
source $HOME/.dots/zsh/cmus.zsh
source $HOME/.dots/zsh/dynamit.zsh


alias sourcezsh="source ~/.zshrc; source ~/.zprofile"

alias ll="ls -Alh"
